SET IDENTITY_INSERT [dbo].[BookGenreModels] ON
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (1, N'Science fiction')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (2, N'Satire')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (3, N'Drama')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (4, N'Action')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (5, N'Adventure')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (6, N'Romance')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (7, N'Mystery')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (8, N'Horror')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (9, N'Self help')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (10, N'Health')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (11, N'Guide')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (12, N'Travel')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (13, N'Religion')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (14, N'Science')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (15, N'Math')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (16, N'Programming')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (17, N'Computers')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (18, N'Computer science')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (19, N'Social science fiction')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (20, N'Novel')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (21, N'Dystopian fiction')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (22, N'Utopian fiction')
INSERT INTO [dbo].[BookGenreModels] ([Id], [Name]) VALUES (23, N'Fantasy')
SET IDENTITY_INSERT [dbo].[BookGenreModels] OFF
