SET IDENTITY_INSERT [dbo].[BookModels] ON
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (1, N'Harry Potter and the Philosopher''s Stone', N'J.K.Rowling', 1997, NULL, CAST(45.00 AS Decimal(18, 2)), 23, 3, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (2, N'Harry Potter and the Chamber of Secrets', N'J.K.Rowling', 1998, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 4, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (3, N'Harry Potter and the Prisoner of Azkaban', N'J.K.Rowling', 1999, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 5, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (4, N'Harry Potter and the Goblet of Fire', N'J.K.Rowling', 2000, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 6, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (5, N'Harry Potter and the Order of the Phoenix', N'J.K.Rowling', 2003, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 7, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (6, N'Harry Potter and the Half-Blood Prince', N'J.K.Rowling', 2005, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 8, null, N'image/jpeg')
INSERT INTO [dbo].[BookModels] ([Id], [Name], [Author], [ReleaseYear], [Description], [Price], [BookGenreModels_Id], [MovieModels_Id], [ImageData], [ImageMimeType]) VALUES (7, N'Harry Potter and the Deathly Hallows', N'J.K.Rowling', 2007, NULL, CAST(215.00 AS Decimal(18, 2)), 23, 9, null, N'image/jpeg')
SET IDENTITY_INSERT [dbo].[BookModels] OFF
