SET IDENTITY_INSERT [dbo].[MovieGenreModels] ON
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (1, N'Action')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (2, N'Adventure')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (3, N'Comedy')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (4, N'Crime & Gangster')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (5, N'Drama')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (6, N'Epics')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (7, N'Historical')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (8, N'Horror')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (9, N'Musicals')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (10, N'Science fiction')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (11, N'War')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (12, N'Westerns')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (13, N'Thriller')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (14, N'Animation')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (15, N'Mystery')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (16, N'Philosophical')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (17, N'Political')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (18, N'Saga')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (19, N'Satire')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (20, N'Social')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (21, N'Urban')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (22, N'Dystopian fiction')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (23, N'Utopian fiction')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (24, N'Social science fiction')
INSERT INTO [dbo].[MovieGenreModels] ([Id], [Name]) VALUES (25, N'Fantasy')
SET IDENTITY_INSERT [dbo].[MovieGenreModels] OFF
